swagger2:
  apiInfo:
    title: Title
    version: 1.0
    description: Swagger-UI
    contact:
      name: zhuxj
      url: http://127.0.0.1
      email:
  apis:
    basePackage: org.zipper.demo.zdemo
logging:
  level:
    root: info

shiro:
  realm:
    class: org.zipper.demo.zdemo.DemoRealm